name: Maven Run Tests when push to Main branch
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Create certs directory
        run: mkdir -p src/main/java/resources/certs
      - name: Generate keypair.pem
        run: openssl genrsa -out src/main/java/resources/certs/keypair.pem 2048
      - name: Generate public.pem
        run: openssl rsa -in src/main/java/resources/certs/keypair.pem -pubout -out src/main/java/resources/certs/public.pem
      - name: Generate private.pem
        run: openssl pkcs8 -topk8 -inform PEM -outform PEM -nocrypt -in src/main/java/resources/certs/keypair.pem -out src/main/java/resources/certs/private.pem
      - name: Test with Maven
        run: mvn -B test --file pom.xml
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Build with Maven
        run: mvn -B package --file pom.xml
